ci:
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: '[misc] Update pre-commit hooks'

default_language_version:
    python: python3.10

exclude: ^((tests/python/test_exception)\.py$|external/)
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.10
        args: ['-l', '120']

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        exclude: .*\.json$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        args: ['-rn', '-sn']
        files: ^python/gstaichi/
