name: Linux
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'self-hosted-runner-gh200']
    name: Linux Build
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Linux prerequisites
        run: |
          bash .github/workflows/scripts_new/linux/1_prerequisites.sh
      - name: Linux build
        run: |
          bash .github/workflows/scripts_new/linux/2_build.sh
      - name: Linux install
        run: |
          bash .github/workflows/scripts_new/linux/3_install.sh
      - name: Linux test
        run: |
          bash .github/workflows/scripts_new/linux/4_test.sh
