name: Pyright linter
on:
  workflow_call:
    inputs:
      head_ref:
        description: 'The head ref (branch name or PR ref)'
        required: true
        type: string
      artifact_name:
        description: 'Name of the artifact to download'
        required: true
        type: string
  workflow_dispatch:
jobs:
  build:
    name: Pyright Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install stubs, from wheel, and dev install gstaichi
        run: |
          set -x
          mkdir -p dist
          mv *.whl dist/
          ls -lh dist/
          unzip dist/*.whl -d dist
          mkdir -p stubs/gstaichi/_lib/core
          cp dist/gstaichi/_lib/core/gstaichi_python.pyi stubs/gstaichi/_lib/core/
          touch stubs/gstaichi/_lib/core/py.typed
          pip install setuptools_scm
          pip install -e .
      - name: install torch and pyright
        run: |
          pip install torch pyright
      - name: run pyright
        run: |
          pyright
